name: Create static page

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install -r requirements.txt
      - run: > 
          ART_ID=$(curl -L -H "Accept: application/vnd.github+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          "https://api.github.com/repos/eugene-okulik/pages/actions/artifacts?name=allure-result" 
          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);")
          && curl -L
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.MY_PERSONAL_TOKEN }}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/repos/eugene-okulik/pages/actions/artifacts/$ART_ID/zip -o artifacts.zip
          && REPORT_ID=$(curl -L -H "Accept: application/vnd.github+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          "https://api.github.com/repos/eugene-okulik/pages/actions/artifacts?name=github-pages" 
          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);")
          && curl -L
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.MY_PERSONAL_TOKEN }}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/repos/eugene-okulik/pages/actions/artifacts/$REPORT_ID/zip -o old_report.zip
      - run: mkdir allure-result && unzip artifacts.zip -d allure-result && ls && ls allure-result
      - run: mkdir old-report && unzip old_report.zip -d old-report && ls && ls old-report
      - run: cp old-report/history/history.json old-report/history/history-trend.json allure-result
      - run: python -m pytest --alluredir=allure-result
      - name: Archive allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-result
          path:
            allure-result
          retention-days: 5
      - uses: actions/setup-java@v3
        if: always()
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.22.4/allure-2.22.4.tgz && sudo tar -zxvf allure-2.22.4.tgz -C /opt/ && sudo ln -s /opt/allure-2.22.4/bin/allure /usr/bin/allure
        if: always()
      - run: allure generate -c allure-result -o _site
        if: always()
      - name: Archive generated report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path:
            _site
          retention-days: 5
      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v1.2.9
